version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Windows（WSL2）を含む各環境でホットリロード（ファイルの監視変更）を確実に動作させるための設定
      - WATCHPACK_POLLING=true
